language: node_js
node_js: 6
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - sudo apt-get install build-essential libudev-dev
services:
  - postgresql
env:
  - username=postgres password="" dbname=postgres
