language: node_js
node_js: 6
before_script:
  - echo "PORT=9000" >> .env
  - psql -c 'create database travis_ci_test;' -U postgres
services:
  - postgresql
env:
  - username=postgres password="" dbname=postgres
